---  

apiVersion: v1
kind: ConfigMap
metadata:
  name: apmangular-des
  namespace: procergs-apm   # namespace para deploy
data:
# Variáveis de ambiente para uso em teste no k8s
# Documentacao: http://desenvolvimento.blog.intra.rs.gov.br/2018/08/31/soeauth/
  SOE_AUTH: https://soe.intra.rs.gov.br/soeauth-des/.well-known/openid-configuration
  SOE_PROFILE: https://soe.intra.rs.gov.br/soeauth-des/profile.xhtml
  SOE_CLIENT_ID: apm.i2.des.51nVIiJqkTi04HIPqA3
  SERVER_URL: https://apmnet4-api.des.intra.rs.gov.br/api/v1
  CLIENT_URL: https://apm-angular.des.intra.rs.gov.br

---

apiVersion: apps/v1
kind: Deployment
metadata:  
  name: apm-angular
  namespace: procergs-apm        # namespace para deploy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: apmangular
  template:
    metadata:
      labels:
        app: apmangular
    spec:

      #securityContext:
      #  runAsUser: 101                        # usuario para exeuctar o container  ( /etc/passwd )
      #  fsGroup: 12893                        # grupo JBOSS para acesso ao sistema de arquivos.

      containers:

        - image: __IMAGE__                      # variavel substituida pelo Jenkinsfile
          name: apmangular
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 8080             # porta padrao do container.
                          
          env:
          - name: TZ
            value: America/Sao_Paulo

          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name  

          envFrom:
          - configMapRef:  
              name: apmangular-des
            
          securityContext:
            allowPrivilegeEscalation: false 
            seccompProfile:
              type: RuntimeDefault
            capabilities:          
              drop:
                - SYS_ADMIN         # >>  << !! Allow privilete Escalation!
                - SYS_RESOURCE      # >>  << !1 Override sistem limits !
                - SETPCAP           # >>  << !! process can manipulate its own capabilities
                - MKNOD             # >>  << !! allows a process to create device nodes in the filesystem (printers,mouse, pseudo-devices)                               
                - FSETID            # >>  << !! used to bypass file system permission checks and manipulate file ownership and permissions

          resources:
            requests:
               memory: 50Mi
               cpu: 0.1
            limits:
               memory: 200Mi
               cpu: 0.3

          livenessProbe:                          # testa se o container está ativo.
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1