# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - develop

pool:
  name: PROCERGS

steps:
# Instala o Node
- task: NodeTool@0
  inputs:
    versionSpec: '20.12.x'
  displayName: 'Install Node.js'

# Autenticação
- task: npmAuthenticate@0
  inputs:
    workingFile: './.npmrc'

# Instala as dependências do projeto
- task: Npm@1
  displayName: 'Npm Install'
  inputs:
    command: 'install'

# Roda testes do Jest
- task: Npm@1
  displayName: 'Run test coverage Jest'
  inputs:
    command: 'custom'
    customCommand: 'test -- --coverage'


# Executa o build
- task: Npm@1
  displayName: 'Run npm build'
  inputs:
    command: 'custom'
    customCommand: 'run build'