#
# Template contendo os jobs para o Deploy(Release) da aplicação Angular para os servidore IIS atravéz do LVP
#
parameters:
  environment: ''
  ambienteLVP: ''
  sistema: ''
  grupoMaquinas: ''
  pastaServidorAplicacao: ''
  pastaPublicacao: ''
  pastaDestino: ''
  matriculaSOE: ''
  senhaSOE: ''

jobs:
  #
  # Job 1 - Limpa pasta da aplicação no servidor (via LVP)
  #
  - deployment: LimpaPasta
    displayName: 'Limpa pasta da aplicação no servidor (via LVP)'
    environment: '${{ parameters.environment }}'
    strategy:
        runOnce:
          deploy:
            steps:
              - task: CopyFiles@2
                displayName: 'Copia arquivos publicados para a pasta temporária'
                inputs:
                  SourceFolder: '${{ parameters.pastaServidorAplicacao }}'
                  TargetFolder: '${{ parameters.pastaPublicacao }}\LimparTmp'

              - task: LVPCriaCabecalho@2
                displayName: 'LVP: Cabeçalho'
                inputs:
                  Sistema: '${{ parameters.sistema }}'
                  SO: 'W'
                  Ambiente: '${{ parameters.ambienteLVP }}'
                  Agendamento: '-'
                  Forcada: true
                  CriaPastas: true
                  Rapida: true
              
              - task: LVPIncluiItem@2
                displayName: 'LVP: Excluí todos arquivos da pasta do servidor'
                inputs:
                  TipoObjeto: 'D'
                  LocalOrigem: '${{ parameters.pastaPublicacao }}\LimparTmp'
                  GrupoMaquinas: '${{ parameters.grupoMaquinas }}'
                  PastaDestino: '${{ parameters.pastaDestino }}'
                  AcaoExcluir: true
              
              - task: LVPExecutaLiberacao@2
                displayName: 'LVP - Executa Liberação'
                inputs:
                  Matricula: '${{ parameters.matriculaSOE }}'
                  Senha: '${{ parameters.senhaSOE }}'
              
              - task: DeleteFiles@1
                displayName: 'Limpa pasta temporária'
                inputs:
                  SourceFolder: '${{ parameters.pastaPublicacao }}\LimparTmp'
                  Contents: '**'
  #
  # Job 2 - Libera nova versão (via LVP)'
  #
  - deployment: LiberaVersao
    displayName: 'Libera nova versão (via LVP)'
    environment: '${{ parameters.environment }}'
    dependsOn: LimpaPasta
    strategy:
        runOnce:
          deploy:
            steps:
              - task: replacetokens@5
                displayName: 'Replace tokens in app-config-template.json => app-config.json'
                inputs:
                  rootDirectory: '${{ parameters.pastaPublicacao }}\dist\assets'
                  targetFiles: 'app-config-template.json => app-config.json'
                  tokenPattern: custom
                  tokenPrefix: '${'
                  tokenSuffix: '}'
                  actionOnMissing: fail
                  actionOnNoFiles: fail
              
              - task: LVPCriaCabecalho@2
                displayName: 'LVP - Cabeçalho'
                inputs:
                  Sistema: '${{ parameters.sistema }}'
                  SO: 'W'
                  Ambiente: '${{ parameters.ambienteLVP }}'
                  Agendamento: '-'
                  Forcada: true
                  CriaPastas: true
                  Rapida: true
              
              - task: LVPIncluiItem@2
                displayName: 'LVP - Inclui Itens na Liberação'
                inputs:
                  TipoObjeto: 'D'
                  LocalOrigem: '${{ parameters.pastaPublicacao }}\dist'
                  GrupoMaquinas: '${{ parameters.grupoMaquinas }}'
                  PastaDestino: '${{ parameters.pastaDestino }}'
              
              - task: LVPExecutaLiberacao@2
                displayName: 'LVP - Executa Liberação'
                inputs:
                  Matricula: '${{ parameters.matriculaSOE }}'
                  Senha: '${{ parameters.senhaSOE }}'
